- CHANGELOG.md
- doc/api.md
- examples/.joyride/scripts/ignore_form.cljs
- src/main/joyride/extension.cljs
- src/main/joyride/nrepl.cljs
- src/main/joyride/sci.cljs
Fixes: #5
It took an embarrassing amount of time for me to figure this out. 😄 But now I think I am starting to get more of it and am glad I didn't give up and tossed it back to you, @borkdude.
These are the minimal changes. I choose to start like this to make the change easier to give and receive feedback on.
I would like to do rename `joyride.sci` to `joyride.core`, because it gets a bit of a mind fuck remembering which `sci` is which.
Also, I updated the example to use this new facility. And then we are now running into the same problem as Calva has with what is on `master` and what is published. The example won't really work with v0.0.2. In Calva we solve it by having a `dev` branch where we direct PRs and accumulate changes, We then merge to the default branch when we release. It …
> Add `joyride.core` namespace w/ `*file*`

- CHANGELOG.md
- package.json
- shadow-cljs.edn
- src/main/joyride/extension.cljs
The command for running a piece of code was named `runScript`, which implied it worked similar to the runWorkspaceScript command, which it doesn't. It prompted for the user to input code, and disregarded any argument. The result of evaluating the code was then alerted, causing noice in the UI.
The command is now renamed. to `runCode` and will evaluate the argument, if handed one, as code. And without any argument it will prompt for code, as before. The results are printed in the Joyride output channel, where it can be copied to the clipboard, or whatever.
While doing this work, I noticed I was losing the output channel reference when I saved the file. Which was because the `!db` item was `def`ed instead of `defonce`ed. I decided to put in a proper lifecycle managament with shadow-cljs …
> More proper run code command and fix dev reloadability

- doc/api.md
- examples/.joyride/scripts/joyride_api.cljs
- playground/hello-joyride/.joyride/scripts/hello.cljs
- src/main/joyride/extension.cljs
- src/main/joyride/sci.cljs
Adds a function to `joyride.core` for getting the Joyride extension context.
Fixes #33
> Add get-extension-context to joyride.core

- doc/api.md
- examples/.joyride/scripts/activate.cljs
- examples/.joyride/scripts/fontsize.cljs
- examples/.joyride/scripts/ignore_form.cljs
- examples/.joyride/scripts/open_document.cljs
- examples/.joyride/scripts/terminal.cljs
- examples/.joyride/scripts/webview/example.cljs
- src/main/joyride/extension.cljs
- src/main/joyride/sci.cljs
Adds a function `get-invoked-script` to `joyride.core` that will be set when a script is run, but not otherwise.
Docs and examples updated accordingly.
Fixes #4
> Add `joyride.core/get-invoked-script`

- README.md
- doc/api.md
- examples/.joyride/scripts/activate.cljs
- examples/.joyride/scripts/fontsize.cljs
- examples/.joyride/scripts/ignore_form.cljs
- examples/.joyride/scripts/joyride_api.cljs
- examples/.joyride/scripts/open_document.cljs
- examples/.joyride/scripts/terminal.cljs
- examples/.joyride/scripts/webview/example.cljs
- examples/README.md
- playground/hello-joyride/.joyride/scripts/hello.cljs
- src/main/joyride/db.cljs
- src/main/joyride/extension.cljs
- src/main/joyride/nrepl.cljs
- src/main/joyride/sci.cljs
- src/main/joyride/utils.cljs
- src/main/joyride/when_contexts.cljs
* Stops always showing the Joyride output channel on script runs
* Adds `joyride.core/get-output-channel` function
* Update to Joyride API example
Fixes #36
NB: This PR builds on to of #39, so please review that one first.
> Add output channel access API

- CHANGELOG.md
- src/main/joyride/extension.cljs
- src/main/joyride/utils.cljs
We were catching the file not found error when reading the script and logging the error to the JS console. Now we catch the error ”at the edge” and print it to the Joyride output channel, and show it.
Fixes #40
> Don't catch error when reading script

- src/main/joyride/sci.cljs
fixes #38 
With this change, `(require)` checks the workspace scripts directory first, then the user script directory, then fails. It incidentally also adds a nil check on the workspace root before trying to load it, so in cases where Joyride currently complains about a null when requiring a script with no workspace loaded, this prevents the call to `path/join` if there's no workspace root. Finally, if there's no matching file in the workspace or user scripts directory, Joyride currently presents a JS-ish error message (`ENOENT`). This change returns nil from sci's `:load-fn` if no matching files are found, resulting in the message `Could not find namespace: missing-ns`.
It does still use the synchronous fs stuff for now.
> add user script directory to search paths of 'require'

- CHANGELOG.md
- deps.edn
- doc/api.md
- package.json
- src/joyride/sci.cljs
Trying to get at `p/handle` et al, which were added in a more recent sci.configs.
However, right now not getting it to work, even though it works if I use `:local/deps`
Seeing the same in `nbb`, I think:
```
% npx nbb -e "(require 'promesa.core) promesa.core/handle"
Need to install the following packages:
nbb
Ok to proceed? (y) 
----- Error --------------------------------------
Message:  Could not resolve symbol: promesa.core/handle
Location: 1:25
Phase:    analysis
Could not resolve symbol: promesa.core/handle
```
UPDATE: That was not so, `npx` seems to give me some old version:
```
npx nbb --version                                       
Need to install the following packages:
nbb
Ok to proceed? (y) 
----- Error --------------------------------------
Message:  ENOENT: no such file or …
```
> WIP: Use latest sci.configs

- CHANGELOG.md
- README.md
- deps.edn
- doc/api.md
- examples/.joyride/scripts/joyride_api.cljs
- examples/.joyride/scripts/z_joylib/calva_api.cljs
- src/joyride/sci.cljs
I don't really know what I am doing...
I think I am close because:
```clojure
(ns my-lib
(:require ["vscode" :as vscode]
["betterthantomorrow.calva$v0" :as calva-js]
[joyride.core :as joyride]
[promesa.core :as p]))
calva-js/repl ; => #js {:evaluateCode #object[Function], :currentSessionKey #object[Function]}
calva-js/repl.evaluateCode ; => #object[Function]
```
But:
```clojure
(-> (calva-js/repl.evaluateCode "42")
(p/then (fn [v]
(js/console.log v)))
(p/catch (fn [e]
(println "Error:" e)))) ; => Error: Error: No protocol method ICounted.-count defined for type number: 0
```
Fixes #71
> Enable requiring extension exports as JS lib

- CHANGELOG.md
- README.md
- assets/getting-started-content/user/user_activate.cljs
- assets/getting-started-content/workspace/workspace_activate.cljs
- examples/.joyride/scripts/workspace_activate.cljs
- examples/README.md
- src/joyride/getting_started.cljs
- src/joyride/life_cycle.cljs
- src/joyride/scripts_handler.cljs
Prefixing `activate.cljs` files with the respective ”section”, so `user_activate.cljs` and `workspace_activate.cljs`. Also reverting the temporary rename of the symbols in these files, as they no longer conflict/compete.
Fixes #73
> Prefix activation script names with ”classpath”

- CHANGELOG.md
- src/joyride/sci.cljs
We were missing to add `promesa.protocols` to the builtin namespaces.
Fixes #85
> Add missing `promesa.protocols` namespace

- CHANGELOG.md
- src/joyride/extension.cljs
On dev reload, correctly call `dispose` method of each disposable
before resetting the vector of stored disposables. Fixes #87
> Dispose disposables before discarding them.

- CHANGELOG.md
- README.md
- doc/configuration.md
- package.json
- src/joyride/extension.cljs
- src/joyride/nrepl.cljs
Add a setting `joyride.nReplHostAddress` with a default of `"127.0.0.1"`.
Fixes #102
The error handling is a bit lacking. Not sure how it is supposed to be done. But I added a listener for the `error` event and also sanity check the host address provided.
> Add configuration for nrepl port address

- CHANGELOG.md
- package.json
The shortcuts were weird. And behaved weirdly with some keyboard layouts. I've changed them. They are all starting with `ctrl+alt+j` now. Should be easy to remember, I hope.
> Change default keyboard shortcut bindings

- CHANGELOG.md
- src/joyride/nrepl.cljs
The Clojure/Java nrepl server uses a wrapper around `pprint/write` when pretty printing. Thinking we can do as well, except I didn't see a need for wrapping.
Also adding `clojure.core/pr` as a pretty print function.
Fixes:
* #108
> Use pprint/write instead of pprint/pprint

- script/bundle-compare.sh
- script/bundle-load-check.js
- script/load-time.js
- script/mock-vscode/.gitignore
- script/mock-vscode/node_modules/vscode/index.js
- src/joyride/extension.cljs
* Measuring the time it takes from start to end of extension `activate()`
* Added some utility scripts for comparing load times between bundles
Example run of a comparison:
```
% script/bundle-compare.sh /Users/pez/.vscode/extensions/betterthantomorrow.joyride-0.0.32 /Users/pez/Downloads/joyride-0.0.33-rewrite-clj-77ebb270/extension 100
Comparison of:
1. /Users/pez/.vscode/extensions/betterthantomorrow.joyride-0.0.32
Size: 1351978 bytes
Load time average: 48.33 ms
2. /Users/pez/Downloads/joyride-0.0.33-rewrite-clj-77ebb270/extension
Size: 1591118 bytes
Load time average: 55.13 ms
Loaded the bundles 100 times each.
Size difference: 239140  (17.6%)
Load time difference: 6.806672046184534  (14.0%)
```
> Add activation timing logging to the extension + scripts for comparing load times

- examples/README.md
Just a documentation fix. The link for `examples/.joyride` was broken...it went to `examples/examples/.joyride` instead. Relative URLs can be confusing!
> :memo: Fix broken link in examples

- cljfmt.edn
- src/joyride/nrepl.cljs
- src/joyride/repl_utils.cljs
Fixes the eval and also completions. Same root problem:
We were treating the sci context as if it was an IDeref, but it is just a map, as in “Just use maps!”.
I'll return to this. Scouts honor!
- ~[ ] I have updated the **\[Unreleased\]** section of the [CHANGELOG.md]~(https://github.com/BetterThanTomorrow/joyride/blob/master/CHANGELOG.md) file with a link to the addressed issue.
> 171 nrepl ns field eval

- .joyride/deps.edn
- CHANGELOG.md
- assets/getting-started-content/user/deps.edn
- assets/getting-started-content/workspace/deps.edn
- examples/.clj-kondo/funcool/promesa/config.edn
- examples/.clj-kondo/rewrite-clj/rewrite-clj/config.edn
- examples/.joyride/deps.edn
- examples/.lsp/config.edn
- examples/deps.edn
- src/joyride/getting_started.cljs
OK. So I was too trigger happy with adding Joyride user script config to the Joyride workspace deps.edn. Reverting that here and replacing with instructions on how to use the global/user deps.edn for this.
* Fixes #176
> User deps revert

- CHANGELOG.md
- deps.edn
- src/joyride/sci.cljs
- Using `:ns-aliases` to alias `clojure.repl` as `cljs.repl`.
- Adding a `clojure.repl/pst` fn that throws a **not yet implemented** error. (Because SCI does not yet implement `pst` for `cljs`.
> Make requiring utils from `cljs.repl` work

- CHANGELOG.md
- src/joyride/lm_tool.cljs
This is WIP, but improves things a lot so I'm going to release:
* Fixes #202
> Capture stdout for LM tool when waiting for promises

- CHANGELOG.md
- src/joyride/sci.cljs
- vscode-test-runner/workspace-1/.joyride/src/integration_test/joyride_core_test.cljs
Stop resetting the currrent namespace from that the loaded file.
* Fixes #229
No tests confirming, because I can't figure out how to test it. But I tested manually in the repl and left disabled tests that show my latest attempts. I think it may not be quite possible to test it with the test runner and current the current sci environment in Joyride?
> Load-file-current-ns

- CHANGELOG.md
- src/joyride/nrepl.cljs
This issue fixes closing the session for clients like vim-fireplace that actively wait for "session-closed" in the reply.
> Fix nrepl close for vim-fireplace
