README.md
=> A really small typo 😅 

CHANGELOG.md, doc/configuration.md, package.json, src/main/joyride/config.cljs, src/main/joyride/extension.cljs, src/main/joyride/sci.cljs, src/main/joyride/scripts_menu.cljs, src/main/joyride/settings.cljs
This is mostly a refactoring to allow the workspace and user script to mainly be a configurations of the same ”run script” functionality. But we also actually add user scripts. 😄
=> Add user scripts

CHANGELOG.md, src/main/joyride/extension.cljs
=> Check if we have picked script before running it

src/main/joyride/extension.cljs
=> Very important text update

CHANGELOG.md, src/main/joyride/nrepl.cljs
Fixes https://github.com/BetterThanTomorrow/joyride/issues/49
=> nrepl: support pprinting eval results

CHANGELOG.md, assets/getting-started-content/user/activate.cljs, assets/getting-started-content/user/my_lib.cljs, examples/README.md, src/main/joyride/getting_started.cljs
=> Add clojure-lsp my-lib example

CHANGELOG.md, doc/api.md, src/joyride/extension.cljs
Makes the runCode command return results.
Fixes #98
=> Return results from run-code

CHANGELOG.md, package.json
=> Change default keybinding for run user script

CHANGELOG.md, doc/api.md, examples/.joyride/scripts/find_in_html.cljs, examples/.joyride/scripts/ignore_form.cljs, examples/.joyride/scripts/ws.cljs, examples/.joyride/src/README.md, examples/.joyride/src/calva_api.cljs, examples/.joyride/src/clojure_symbols.cljs, examples/.joyride/src/hickory/select.cljs, examples/.joyride/src/hickory/zip.cljs, examples/.joyride/src/util/editor.cljs, examples/.joyride/src/util/workspace.cljs, examples/README.md, src/joyride/config.cljs, src/joyride/sci.cljs
=> Add `src` sub directories to classpath

CHANGELOG.md, deps.edn, doc/api.md, src/joyride/sci.cljs
Bump sci and sci-configs
* Fixes #121
* Fixes #122
=> Bump sci and sci-configs

src/joyride/sci.cljs
@PEZ Can you merge this and try with your js script PR?
=> Add require explicitly

CHANGELOG.md, deps.edn, src/joyride/sci.cljs, vscode-test-runner/workspace-1/.joyride/src/integration_test/rewrite_clj_test.cljs, vscode-test-runner/workspace-1/.joyride/src/integration_test/runner.cljs
=> Fix #150: include rewrite-clj

.circleci/config.yml, CHANGELOG.md, package-lock.json, package.json, vscode-test-runner/launch.js, vscode-test-runner/workspace-1/.joyride/src/integration_test/runner.cljs
Adding an integration test of the VSIX in addition to testing from the filesystem.
* Fixes #154
=> vsix+fs testing

examples/README.md
Added a simple example that builds on the find-in-file example, to demo customizing workspace search settings.
(no test required).
N/A
=> Update readme, customize workplace search

examples/.joyride/scripts/toggle_between_interface_and_impl.cljs, examples/README.md
**I didn't do the following, since this is just a new example:**
=> New example: toggle between interface and implementation

CHANGELOG.md, src/joyride/sci.cljs, vscode-test-runner/workspace-1/.clj-kondo/http-kit/http-kit/config.edn, vscode-test-runner/workspace-1/.clj-kondo/http-kit/http-kit/httpkit/with_channel.clj, vscode-test-runner/workspace-1/.joyride/deps.edn, vscode-test-runner/workspace-1/.joyride/src/integration_test/tap_test.cljs
=> Add `tap>` et al

CHANGELOG.md, assets/getting-started-content/user/deps.edn, assets/getting-started-content/workspace/deps.edn
=> Update `:source-aliases` recommendation in auto-created workspace `.joyride/deps.edn`

CHANGELOG.md, deps.edn, doc/api.md, src/joyride/sci.cljs
=> Bump to latest SCI

CHANGELOG.md, src/joyride/sci.cljs
=> Add uuid constructor to sci

CHANGELOG.md, examples/.joyride/scripts/clojars.cljs
Fixes BetterThanTomorrow/joyride#192
=> Add example for searching clojars

CHANGELOG.md, doc/api.md, src/joyride/sci.cljs, vscode-test-runner/workspace-1/.joyride/src/integration_test/joyride_core_test.cljs
=> Provide access to the user joyride directory via `joyride.core/user-joyride-dir`

doc/api.md, examples/README.md
**PR Summary**:
This PR reviews and resolves issues in the `doc/api.md` and `examples/README.md` doc files.
=> Resolve issues with the API and examples docs 

CHANGELOG.md, src/joyride/content_utils.cljs, vscode-test-runner/workspace-1/.joyride/src/integration_test/activate_test.cljs
=> Create .gitignore from user default content

CHANGELOG.md, package.json, src/joyride/extension.cljs, src/joyride/lm.cljs, src/joyride/lm/core.cljs, src/joyride/lm/docs.cljs, src/joyride/lm/eval.cljs, src/joyride/lm/eval/core.cljs, test/joyride/lm/eval/core_test.cljs, vscode-test-runner/workspace-1/.clj-kondo/taoensso/encore/config.edn, vscode-test-runner/workspace-1/.clj-kondo/taoensso/encore/taoensso/encore_hooks.clj
Also restructures the lm tools code a bit to make room for more tools than eval.
=> 214 agent joyride knowledge tool

CHANGELOG.md, package.json, src/joyride/scripts_handler.cljs
=> 183 quote windows paths

CHANGELOG.md, package.json, src/joyride/lm.cljs, src/joyride/lm/human_input.cljs, src/joyride/lm/human_intelligence.cljs
=> Add Human Intelligence Copilot tool
